[build]
  functions = "netlify/functions"
  publish   = "public"

[functions]
  node_bundler = "esbuild"

[[functions.included_files]]
  path = "netlify/functions/template.pdf"

[[functions.included_files]]
  path = "netlify/functions/malgun.ttf"

[[functions.included_files]]
  path = "netlify/functions/KT_mapping_legacy_names.json"
