[build]
  publish   = "public"
  functions = "netlify/functions"

[functions]
  node_bundler   = "esbuild"
  included_files = [
    "netlify/functions/template.pdf",
    "netlify/functions/malgun.ttf",
    "netlify/functions/KT_mapping_legacy_names.json"
  ]
