[functions]
  node_bundler = "esbuild"
  included_files = [
    "netlify/functions/KT_mapping_legacy_names.json",
    "netlify/functions/malgun.ttf",
    "netlify/functions/template.pdf"
  ]

[build]
  publish = "public"
  functions = "netlify/functions"